/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Hotel.GUI.Recepcionista.TipoPago;

import Hotel.GUI.Recepcionista.CheckIn.CheckInConReservacion;
import Hotel.GUI.Recepcionista.CheckIn.SinReservacion;
import Hotel.GUI.Recepcionista.CheckOut.CheckOut;
import RUN.DefaultValues;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author angelrg
 */
public class Efectivo extends javax.swing.JFrame {

    private String totalPago;
    private String estado;
    
    private CheckInConReservacion checkInConR;
    private SinReservacion checkInSinR;
    private CheckOut checkOut;
    public Efectivo(Connection conexion) {
        checkInConR = new CheckInConReservacion(conexion);
        checkInSinR = new SinReservacion(conexion);
        checkOut = new CheckOut(conexion);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        totalTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pagarButton = new javax.swing.JButton();
        regresarButton = new javax.swing.JButton();
        montoFormattedTextField = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();

        setTitle("Pago");

        jLabel1.setText("Total a pagar:");

        jLabel2.setText("Monto de pago:");

        pagarButton.setText("Pagar");
        pagarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagarButtonActionPerformed(evt);
            }
        });

        regresarButton.setText("Regresar");

        montoFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        jLabel3.setFont(new java.awt.Font("Noto Sans UI", 0, 10)); // NOI18N
        jLabel3.setText("Ej: 12345.6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(pagarButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(regresarButton)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(totalTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(montoFormattedTextField)))
                        .addGap(0, 12, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(totalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(montoFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regresarButton)
                    .addComponent(pagarButton))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pagarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagarButtonActionPerformed
        if (montoFormattedTextField.getText().replace(" ","").replace(".","").isEmpty()) {
            JOptionPane.showMessageDialog(this,"Debe ingresar ingresar un monto", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            if ((Double.parseDouble(montoFormattedTextField.getText())-Double.parseDouble(totalTextField.getText())) < 0) {
                JOptionPane.showMessageDialog(this,"Monto menor al pago necesario", "Error", JOptionPane.ERROR_MESSAGE);
            }else{
                if (estado.equalsIgnoreCase(DefaultValues.PAGO_ALOJAMIENTO)) {
                    limpiar();
                    checkInConR.validarPago(false, "");
                    this.setVisible(false);
                }else if (estado.equalsIgnoreCase(DefaultValues.PAGO_SIN_RESERVACION)) {
                    limpiar();
                    checkInSinR.validarPago(false, "");
                    this.setVisible(false);
                }
            }
        }
    }//GEN-LAST:event_pagarButtonActionPerformed

    public void pagar(String total,String estado){
        limpiar();
        totalTextField.setText(total);
        totalTextField.setEnabled(false);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JFormattedTextField montoFormattedTextField;
    private javax.swing.JButton pagarButton;
    private javax.swing.JButton regresarButton;
    private javax.swing.JTextField totalTextField;
    // End of variables declaration//GEN-END:variables

private void limpiar(){
    montoFormattedTextField.setText("");
    totalTextField.setText("");
}
}
