/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Hotel.GUI.Recepcionista.TipoPago;

import Hotel.BackEnd.Excepciones.InputsVaciosException;
import Hotel.BackEnd.Hotel.Reservacion;
import Hotel.BackEnd.Manejador.ReservarHabitacionM;
import Hotel.GUI.Recepcionista.CheckIn.CheckInConReservacion;
import Hotel.GUI.Recepcionista.CheckIn.SinReservacion;
import Hotel.GUI.Recepcionista.CheckOut.CheckOut;
import RUN.DefaultValues;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author angelrg
 */
public class Efectivo extends javax.swing.JFrame {

    private String estado;

    private ReservarHabitacionM manejadorReservacion;

    private Reservacion reservacionSeleccionada;

    public Efectivo(Connection conexion) {
        manejadorReservacion = new ReservarHabitacionM(conexion);

        reservacionSeleccionada = new Reservacion();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        totalTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pagarButton = new javax.swing.JButton();
        regresarButton = new javax.swing.JButton();
        montoFormattedTextField = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();

        setTitle("Pago");

        jLabel1.setText("Total a pagar:");

        jLabel2.setText("Monto de pago:");

        pagarButton.setText("Pagar");
        pagarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagarButtonActionPerformed(evt);
            }
        });

        regresarButton.setText("Regresar");
        regresarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarButtonActionPerformed(evt);
            }
        });

        montoFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        jLabel3.setFont(new java.awt.Font("Noto Sans UI", 0, 10)); // NOI18N
        jLabel3.setText("Ej: 12345.6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(pagarButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(regresarButton)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(totalTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(montoFormattedTextField)))
                        .addGap(0, 12, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(totalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(montoFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regresarButton)
                    .addComponent(pagarButton))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pagarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagarButtonActionPerformed
        try {
            if (montoFormattedTextField.getText().replace(" ", "").replace(".", "").isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe ingresar ingresar un monto", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                if ((Double.parseDouble(montoFormattedTextField.getText()) - Double.parseDouble(totalTextField.getText())) < 0) {
                    JOptionPane.showMessageDialog(this, "Monto menor al pago necesario", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    if (estado.equalsIgnoreCase(DefaultValues.PAGO_ALOJAMIENTO)) {
                        limpiar();
                        if (manejadorReservacion.CheckInConReservacion(reservacionSeleccionada.getIDCliente(), reservacionSeleccionada.getFechaInicial(),
                                reservacionSeleccionada.getFechaFinal(), reservacionSeleccionada.getNoHabitacion(), "Efectivo")) {
                            JOptionPane.showMessageDialog(this, "Fallo durante el pago", "Error", JOptionPane.ERROR_MESSAGE);
                            this.setVisible(false);
                        } else {
                            JOptionPane.showMessageDialog(this, "Pago exitoso" + (Double.parseDouble(montoFormattedTextField.getText()) - Double.parseDouble(totalTextField.getText())), 
                                    "Informacion", JOptionPane.INFORMATION_MESSAGE);
                            limpiar();
                            this.setVisible(false);
                        }
                        this.setVisible(false);
//                    } else if (estado.equalsIgnoreCase(DefaultValues.PAGO_SIN_RESERVACION)) {
//                        
//                        limpiar();
//                        this.setVisible(false);
                    } else if (estado.equalsIgnoreCase(DefaultValues.PAGO_ALIMENTO)) {
                        limpiar();
                        if (manejadorReservacion.CheckOut(reservacionSeleccionada.getIDCliente(), reservacionSeleccionada.getFechaInicial(), 
                                reservacionSeleccionada.getFechaFinal(), reservacionSeleccionada.getNoHabitacion(), "")) {
                            JOptionPane.showMessageDialog(this, "Pago exitoso" + (Double.parseDouble(montoFormattedTextField.getText()) - Double.parseDouble(totalTextField.getText())), "Informacion", JOptionPane.INFORMATION_MESSAGE);
                            limpiar();
                            this.setVisible(false);
                        } else {
                            JOptionPane.showMessageDialog(this, "Fallo durante el pago", "Error", JOptionPane.ERROR_MESSAGE);
                            this.setVisible(false);
                        }

                    }
                }
            }
        } catch (InputsVaciosException | HeadlessException | NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_pagarButtonActionPerformed

    private void regresarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarButtonActionPerformed
        this.setVisible(false);
        limpiar();
    }//GEN-LAST:event_regresarButtonActionPerformed

    public void pagar(String total, String estado, Reservacion reservacion) {
        limpiar();
        totalTextField.setText(total);
        totalTextField.setEnabled(false);
        this.estado = estado;
        reservacionSeleccionada = reservacion;
        setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JFormattedTextField montoFormattedTextField;
    private javax.swing.JButton pagarButton;
    private javax.swing.JButton regresarButton;
    private javax.swing.JTextField totalTextField;
    // End of variables declaration//GEN-END:variables

    private void limpiar() {
        montoFormattedTextField.setText("");
        totalTextField.setText("");
    }
}
